### ISSUE TITLE
max_web_freeze_list_view_header for grid view

### ISSUE THREAD

**Issue by CasVissers** [maxodoo/max-misc-addons#7]
Hi,

Could you please contact me to see if it's possible to make a similar module for the gridview?

Thank you in advance.

Cas

c.vissers at onestein.nl

**Comment by jlzhou** [comment]
what is a gridview?

???? iPhone

? 2017?1?19??16:26?Cas Vissers <notifications@github.com<mailto:notifications@github.com>> ???


Hi,

Could you please contact me to see if it's possible to make a similar module for the gridview?

Thank you in advance.

Cas

c.vissers at onestein.nl<http://onestein.nl>

-

**Comment by CasVissers** [comment]
![2017-01-23 08_48_16-forecast by user - odoo](https://cloud.githubusercontent.com/assets/20641860/22195524/b54d9c4e-e148-11e6-8f6a-3b1c116f1538.png)

The grid view is visible for example in timesheet & project forecast in Odoo 10 enterprise.

**Comment by jlzhou** [comment]
Thank you, but I don't use enterprise so I guess I can't help you on this.

???? iPhone

? 2017?1?23??15:49?Cas Vissers <notifications@github.com<mailto:notifications@github.com>> ???


[2017-01-23 08_48_16-forecast by user - odoo]<https://cloud.githubusercontent.com/assets/20641860/22195524/b54d9c4e-e148-11e6-8f6a-3b1c116f1538.png>

The grid view is visible for example in timesheet & project forecast in Odoo 10 enterprise.

-

**Comment by CasVissers** [comment]
Would it be possible to get a quotation on this?

**Comment by jlzhou** [comment]
Sure, it is possible, but it needs a evaluation at first. What price can you provide?

???? iPhone

? 2017?1?23??16:19?Cas Vissers <notifications@github.com<mailto:notifications@github.com>> ???


Would it be possible to get a quotation on this?

-

**Comment by CasVissers** [comment]
Can you contact me directly on c.vissers@onestein.nl<mailto:c.vissers@onestein.nl> ?


Van: Henry Zhou [mailto:notifications@github.com]
Verzonden: maandag 23 januari 2017 09:27
Aan: maxodoo/max-misc-addons <max-misc-addons@noreply.github.com>
CC: Cas Vissers <c.vissers@onestein.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [maxodoo/max-misc-addons] max_web_freeze_list_view_header for grid view (#7)

Sure, it is possible, but it needs a evaluation at first. What price can you provide?

???? iPhone

? 2017?1?23??16:19?Cas Vissers <notifications@github.com<mailto:notifications@github.com>> ???


Would it be possible to get a quotation on this?

-
